### PR TITLE
Skip remapped globals on cleanup

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes HenrikBengtsson/future#401

Potential solution to the linked issue. This inverts the `cleanup()` loop so that we can skip over globals that have a remapped name. Essentially if the name of the global doesn't exist in the corresponding package environment, then it likely has been remapped by the user manually to a different name.

This alters a single test so that `sum2()` is no longer dropped when running `cleanup(drop = "primitives")`. It makes sense to not drop this, because `sum()` has been remapped to `sum2()`.

I suppose technically a user could still remap to another function name in the same package environment like in the example below, but that would be pretty rare:

```r
> globals <- as.Globals(list(sum = base::identity))
> cleanup(globals)
named list()
attr(,"where")
named list()
attr(,"class")
[1] "Globals" "list"  
```

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Thanks for this patch.  I'll comment more in https://github.com/HenrikBengtsson/future/issues/401 but I agree with the idea behind your patch (I basically re-invented the same idea before noticing this PR).

I'm a bit low of coffee right but regarding but was there a specific reason why you did:

https://github.com/HenrikBengtsson/globals/blob/3aaba3c28040c41d20c9a939878175a2cfd8a205/R/cleanup.R#L45

and not just:
```r
if (is.element(env) && !exists(name, envir = env)) {
```
here?

If not, I'll go ahead and use the latter instead, which made me realize that there's a follow-up bug (non-exported base R objects are still skipped for other reasons - to be continued)

**Comment by HenrikBengtsson** [comment]
Ah... I might see where this is coming from and your comment about `sum2()` above.

**Comment by DavisVaughan** [comment]
I'm fairly certain I was just copying the idea from:

https://github.com/HenrikBengtsson/future/blob/bb2b06ff4ad122f3f31d0f5ed471896472c6572d/R/globals.R#L241-L245

If `asPkgEnvironment()` isn't necessary there either, it looks like instead of:

```r
if (exists(name, envir = asPkgEnvironment(pkg)))
```

you could've used

```r
if (exists(name, envir = where[[name]]))
```

?

**Comment by HenrikBengtsson** [comment]
Ok, I see.  So, I've just spend an hour or so on getting the following to work:
```r
globals <- as.Globals(list(
  identity        = base::identity,
  my_identity     = base::identity,       ## should not be deleted
  print.aspell    = utils:::print.aspell,
  my_print.aspell = utils:::print.aspell  ## should not be deleted
))

names(globals)
## [1] "identity"        "my_identity"     "print.aspell"    "my_print.aspell"

names(cleanup(globals))
## [1] "my_identity"     "my_print.aspell"
```

However, while writing this I realize that if someone does:
```r
print.aspell <- utils:::print.aspell
```
with futures, they clearly do want that non-exported object to remain.  So, internal objects should _not_ be dropped.  Oh well... I'll just unroll ...

**Comment by HenrikBengtsson** [comment]
I think I've got it correct now.  Sorry for the confusing noise here.  The upside of my detour was that there are not checks for globals that are copies of non-exported package objects.

**Pull request merged**
